services:
  topicfs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_UID=${UID:-1000}
        - HOST_GID=${GID:-1000}
        - USERNAME=${USER:-$(id -un)}
    container_name: topicfs
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./:/topicfs/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856